layout_spectrum: 0.1524724557530135
typography_spectrum: 0.1502309455536306
color:
  brandStrength: 0.5586520587094128
  lightness: 0.3119913556147367
  saturation: 0.1747535914182663
  rhythmicContrast: 0.7138941795565188
  brandColors:
    - '#F8F9FC'
    - '#224FAA'
    - '#A62626'
    - '#3D588F'
    - '#C7CAD1'
name: One Earth Community  Blog
navigation:
  - id: 'https://thegrid.ai/one-earth-community/'
    url: 'https://thegrid.ai/one-earth-community/'
    name: back to one earth community
    type: external
